import { auth } from '@/auth';
import { db } from '@/lib/db';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const session = await auth()
	// session?.user.
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
